### ISSUE TITLE
Actions not working properly at slow connections

### ISSUE THREAD

**Issue by tareq-alqadi** [laravel-filament/filament#10195]
### Package

filament/filament

### Package Version

v3.1

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

When click on any action (Create, Edit, Confirmation, etc...) it will appear with no problem, But if you close this modal and try to open this action directly again it will respond at all, because there is two update request not finished yet.  

### Expected behavior

The action should open directly without any delay.

### Steps to reproduce

You can go to demo and throttle your network speed and try any action.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
Unfortunately there is no way we can combat this. Actions heavily rely on having network requests, even when closing. This is actually for performance reasons. Otherwise, every combination of the action modal would need to be stored in the frontend of the app, instead of being fetched on demand by Livewire.

**Comment by danharrin** [comment]
We use loading indicators everywhere to try to combat this. Let me know if there are any missing.
