### ISSUE TITLE
Wrong documentation about installation

### ISSUE THREAD

**Issue by yannisc** [laravel-filament/filament#10684]
### Package

filament/tables

### Package Version

v3.1.35

### Laravel Version

v10

### Livewire Version

v3.0

### PHP Version

irrelevant

### Problem description

Trying to add custom tailwind classes, I followed the installation guide here https://filamentphp.com/docs/3.x/tables/installation#configuring-your-layout and saw that the documentation is not accurate.

1) You should not create a new resources/views/components/layouts/app.blade.php file, but a resources/views/vendor/filament-panels/components/layout/base.blade.php file.
2) You should not paste in it the content shown in the documentation, but the content shown in the original file (vendor/filament-panels/components/layout/base.blade.php and add the line @vite('resources/css/app.css') underneath @filamentStyles.

### Expected behavior

You should be able to add your new tailwind classes that are not currently compiled.

### Steps to reproduce

If you follow the instructions in the current documentation, new tailwind classes are not read neither from app.css nor from any ->recordClasses() methods you may add.

### Reproduction repository

-

**Comment by yannisc** [comment]
How should I send a wrong documentation issue?

**Comment by tonypiper** [comment]
@yannisc (and anyone else who finds themselves having this issue) it seems the fix is to follow the custom theme instructions at https://filamentphp.com/docs/3.x/panels/themes. It's not intuitive, because the filament docs talk about the livewire layout, and that includes vite directives, but that's not used to render a panel. Hope this helps!
