### ISSUE TITLE
Exporter can't export relationships data

### ISSUE THREAD

**Issue by hanaexcl** [laravel-filament/filament#10835]
### Package

filament/filament

### Package Version

v3.2.2

### Laravel Version

v10.10

### PHP Version

v3.3.5

### Problem description

Exporter can't export relationships data, It will export success, but missing relationships data.

### Expected behavior

Export relationships data.

### Steps to reproduce

Create an exporter that includes relationships data.

```php
public static function getColumns(): array
{
    return [
        ExportColumn::make('id'),
        ExportColumn::make('customer.name'), //Missing
    ];
}
```

### Reproduction repository

https://github.com/hanaexcl/filament-export-test

**Comment by maartenpaauw** [comment]
Having the same exact problem. Data from the model directly is working fine, but data from a relationship is not working.

**Comment by ekrist1** [comment]
Same here. Seems to be a bug with JSON columns as well, it's printed out as ARRAY.

**Comment by wannesmatthys** [comment]
Same issue here

**Comment by NicholasMartens** [comment]
Same here

**Comment by akaflipper** [comment]
Same this side ... despite columns being defined in exporter class, on bulk action a modal pops up with column choices to be exported, then on export ignores column definitions in getColumns() in  Exporter::class ... which are defined as make('relationship.name')

**Comment by pvdptje** [comment]
I have located the issue, but I'm not able to provide a fix yet.

in Concerns\CanExportRecords.php on line 129:

``` $columnMap = collect($data['columnMap'])
                ->filter(fn (array $column): bool => $column['isEnabled'] ?? false)
                ->mapWithKeys(fn (array $column, string $columnName): array => [$columnName => $column['label']])
                ->all();
```

The filter() method removes the relation from the columnmap.
The reason is because a relation is a level deeper in the array. Like this:

![image](https://github.com/filamentphp/filament/assets/3110215/ec415a81-bb89-4b37-86ab-5ff2e93f21da)

The ```$column['isEnabled'] ``` will always return false for a relation.

**Comment by pvdptje** [comment]
This fixes the issue for me:

```         
$columnMap = collect($data['columnMap'])
         ->flatMap(function (array $column, string $columnName) {
             // If it's a simple column
             if (isset($column['isEnabled']) && $column['isEnabled']) {
                 return [$columnName => $column['label']];
             }
     
             // If it's a relation
             return collect($column)->filter(function ($subColumn) {
                 return is_array($subColumn) && ($subColumn['isEnabled'] ?? false);
             })->mapWithKeys(function ($subColumn, $subColumnName) use ($columnName) {
                 return ["{$columnName}.{$subColumnName}" => $subColumn['label']];
             })->all();
         })
         ->all();
```

I have created a pull request

**Comment by danharrin** [comment]
#10899

**Comment by darkraul79** [comment]
Are this Closed????

I still have the same issue on v3.2.0

![Captura de pantalla 2024-02-20 124902](https://github.com/filamentphp/filament/assets/9088326/f98ff7d9-98c4-4bd9-90cf-a6c87321b0a9)


When I do the export, it only exports the columns that are not related.

![Captura de pantalla 2024-02-20 125450](https://github.com/filamentphp/filament/assets/9088326/6e96c224-fb62-4b4b-b165-04fd6ad27840)


![Captura de pantalla 2024-02-20 123658](https://github.com/filamentphp/filament/assets/9088326/58dd0da5-fcb8-4e69-b38c-aeccad9eefbd)

Of course, the models are well related, since they appear correctly in the list of records.

![Captura de pantalla 2024-02-20 125538](https://github.com/filamentphp/filament/assets/9088326/73e53e82-2da9-4539-bd46-1a241e4036fa)

**Comment by danharrin** [comment]
It was released in [v3.2.4](https://github.com/filamentphp/filament/releases/tag/v3.2.4).

**Comment by khalidmaquilang** [comment]
i have this column `ExportColumn::make('genealogy.upline.full_name'),` and it doesn't work.. `ExportColumn::make('referrer.full_name'),` is fine but when you do a nested relationship.. it doesn't work

**Comment by karimHemina** [comment]
I an having the same issue but with Json fields, anyone has a solution ?
