### ISSUE TITLE
Add table `->searchable()` API

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#11133]

**Comment by omar-bfe** [comment]
is there an issue with the Table CanSearchRecords Concerns because now it is pointing to [this Trait](https://github.com/filamentphp/filament/blob/91cc0ba0f2a5a6edf404340167dd7ad7a22f5c2c/packages/tables/src/Table/Concerns/CanSearchRecords.php)

and do not have the `applySearchToTableQuery` function and so the scout search on the tables do not work.

**Comment by thethunderturner** [comment]
Could you please give more information as to what this means? Searchable in the sense that is searches all fields/cells in the table?
