### ISSUE TITLE
Autosize textarea doesn't work after form validation failed

### ISSUE THREAD

**Issue by YeeJiaWei** [laravel-filament/filament#11428]
### Package

filament/forms

### Package Version

v3.2.28

### Laravel Version

v10.43.0

### PHP Version

PHP 8.2

### Problem description

the textarea return to its original height after validation failed

### Expected behavior

the textarea should remain same height after validation failed

### Steps to reproduce

1. Make a autosize textare
2. Validate textarea content row by row (i'm validate url with line number)
3. Given non url text
4. Bug!

### Reproduction repository

x

**Comment by SimonMacIntyre** [comment]
I can confirm I am experiencing the same bug.

**Comment by SimonMacIntyre** [comment]
I fixed it by modifying `filament/forms/src/Components/Textarea.php` with this change to `$initialHeight`

```php
$textValue = old($statePath, $field->getState($statePath));  // Get the current text value from the Livewire component's state
$lineCount = substr_count($textValue, "\n") + 1;  // Count the number of lines in the text value

$initialHeight = max((($rows ?? 2) * 1.5) + 0.75, $lineCount * 1.5 + 0.75);  // Use the larger of the default initial height or the height based on the line count
```

I don't know the Filament codebase to know whether or not this is actually a suitable way to fix it though. But the issue seems to boil down to the fact that after validation, it just goes back to initial height of 2 rows, even if theres  a bunch of text in that textbox. 

I could make this PR if a maintainer thought this was a suitable way to fix it, but I assume there is some `autosizing` code somewhere that is the 'right' way to fix it or something. Not sure.

**Comment by SimonMacIntyre** [comment]
@danharrin Sorry for the ping, can you leave this issue open despite it not having a public repository with the bug? It's very easy to reproduce. This should be enough to reproduce it on any form by just pasting a bunch of text in, failing validation, and watching the textarea snap back to 2 rows only. 

```php
TextArea::make('input')
      ->required()
      ->live()
      ->autosize()
      ->default('{"key":"value"}')
      ->afterStateUpdated(function ($livewire, Component $component) {
          $validate = $livewire->validateOnly($component->getStatePath());
      })
```

Whether or not this issue is open, I'd love to open a PR to fix it if you can point me in the right direction regarding my previous comment or where to look into autosizing logic. 

Thanks, and really sorry for the ping but this is a clear as day bug!

**Comment by emamalias** [comment]
I experienced the same issue, can be fixed by adding extra alpine attribute to re render after `form-validation-error` event fired

created a pull request #12348 

```php
TextArea::make('input')
      ->required()
      ->live()
      ->autosize()
      ->extraAlpineAttributes([
          'x-on:form-validation-error.window' => '$nextTick(() => render())',
      ])
```
