### ISSUE TITLE
Unable to insert a Builder block between others in a multilingual setup

### ISSUE THREAD

**Issue by AlexisSerneels** [laravel-filament/filament#11541]
### Package

filament/filament

### Package Version

v3.2.35

### Laravel Version

v10.45.1

### PHP Version

PHP 8.3.3

### Problem description

When a Builder is used in a Resource managed by `filament/spatie-laravel-translatable-plugin`, the error `Undefined array key "afterItem"` is returned when trying to insert a block between others.

I was able to trace the error to this line and it arises because the blocks for translations do not have a UUID:
https://github.com/filamentphp/filament/blob/27dca4d0c2dabcf71d9dbcf03cdeb2fd98f8a1ce/packages/forms/src/Components/Builder.php#L190 

Here is the dump for the `$arguments` when saving in English:
![CleanShot 2024-02-23 at 09 50 18@2x](https://github.com/filamentphp/filament/assets/287688/16da79be-7fbd-4506-b94f-7343ecec2273)

Here is the dump for the `$arguments` when saving in other languages.
We can see the UUID and `afterItem` key is missing.
![CleanShot 2024-02-23 at 09 51 00@2x](https://github.com/filamentphp/filament/assets/287688/64df34d2-fa36-49cc-b902-26021292052b)

Here is the full error in video:

https://github.com/filamentphp/filament/assets/287688/3f54d820-4869-4fd1-810f-966288ae856d

### Expected behavior

No error should occur.

### Steps to reproduce

- Clone the repository.
- Migrate
- Seed
- Go to Products, edit any.
- Switch to FRENCH
- Try inserting a block between the two existing.

![CleanShot 2024-02-23 at 09 47 32@2x](https://github.com/filamentphp/filament/assets/287688/8012dc3f-d85c-4b35-b89b-3a94107313da)

### Reproduction repository

https://github.com/AlexisSerneels/filament-issue

**Comment by dmitry-udod** [comment]
@AlexisSerneels Hi! There are two reasons why this happens: When you switch the locale to French in your example, the `spatie-laravel-translatable-plugin` resets the data array keys from uuid's to integers [(plugin code)](https://github.com/filamentphp/filament/assets/4639175/18786da8-c8d0-463a-b1ee-d07dfcb3e11e). Then, in our `block-picker.blade.php`, we have an [if statement](https://github.com/filamentphp/filament/blob/3.x/packages/forms/resources/views/components/builder/block-picker.blade.php#L33) where we check that the `$afterItem` variable is set, but because it has a zero value, it fails. See the video below, please:

https://github.com/filamentphp/filament/assets/4639175/1c87f370-6558-44d1-9b7a-7af05aa03a99

As a quick solution you can create a new class that extends `Filament\Forms\Components\Builder\Block` and create custom view for it with "isset" fix.
