### ISSUE TITLE
Repeater with Spatie Translatable plugin doesnt cast objects

### ISSUE THREAD

**Issue by demianottema** [laravel-filament/filament#11826]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

v3.2.42

### Laravel Version

v11.0

### Livewire Version

v3.4.6

### PHP Version

v8.2.4

### Problem description

When i add a Repeater field in my (edit) resource page, all translations don't work and get replaced with: [object Object]
When i dump the initial state using some code like this:
`TextInput::make("short_title")->afterStateHydrated(function (TextInput $component, string $state) { dump($state); })`
The text is correct. That makes me think the page gets reloaded by a Repeater, maybe to fill its data?
Besides that the repeater creates like 20 empty fields, also strange behaviour.

Something to mention is that i have a table with products and product_variants. The product_variants model is Translatable, but does't have its own page. Maybe it has any effect.

There are some other issues that have the simular problem. (#11175) But none have this behaviour.
![image](https://github.com/filamentphp/filament/assets/44736169/8852b041-7396-45c6-b2b6-51e34ee7dcc4)

### Expected behavior

I expected that the text is in the correct language

### Steps to reproduce

Migrate the database, and check the page called Producten, when you click one you see the problem.
This is my current project, but this was the first resource that i created.

### Reproduction repository
https://github.com/demianottema/TG_Dashboard-V3

**Comment by demianottema** [comment]
@danharrin, What kind of help do you want? Or dont you expect help from me?

**Comment by danharrin** [comment]
Anyone can help by submitting or testing PRs. I've spent so much time on this plugin and its very difficult to balance the behaviour without breaking something else for someone, and there are other parts of the project that need my attention.

**Comment by rasul-chopurov** [comment]
+   TextInput::make('title')
[object][object]

**Comment by dmitry-udod** [comment]
The reproduction repo is no longer accessible.
@demianottema  Can you update the URL, please?

![Screenshot from 2024-04-12 10-20-41](https://github.com/filamentphp/filament/assets/4639175/2c26e71e-5551-424d-a671-ffc0688b27a2)

**Comment by devcbash** [comment]
any news regarding this? for using the plugin with repeaters? and if not what can be a quick fix to get the json returned correctly in a textinput??

**Comment by danharrin** [comment]
_I am posting this same message across all Spatie Translatable issues & PRs_

Hey all! Wanted to update you on where we're at with the translatable plugin.

I really appreciate your patience while this issue has been active. While I created the plugin for the community, I've never actually had a project where I needed to use it, and that's the same for the rest of the Filament team. As such, it's the reason why the plugin hasn't had as much attention as the others, and is much more unstable: I just don't have the environment to test all the use cases, nor the motivation to make it truly great.

As such, I put out a post a month ago and asked who in the community uses the plugin and has knowledge of plugin development. Luckily, Lara Zeus and Mohamed Sabil stepped forward, who are both authors of popular Filament plugins and are trusted by the community.

We are strongly considering handing over maintenance of the plugin to those developers, for the good of the community. You can find their fork at https://github.com/lara-zeus/translatable.

Since the new developers have lots of experience with the plugin and active projects that use it, they should be able to help debug issues easier and make a much more stable experience for other users.

If their work goes well until v4 is released, we will likely retire the plugin at that point and recommend the fork as an official replacement. If it does not go as expected and the community is unhappy, then we will reconsider this decision. **I am closing this for now, and if we decide to take maintenance back officially then we will probably reopen it.**

The existing plugin will continue to receive security updates indefinitely. Please let me know if you have any further questions.

Many thanks,
Dan

**Comment by Khant-Nyar** [comment]
in the model 
you need to cast as array 
 protected $casts = [ 'short_title'=>'array'];

**Comment by veyselaydogdu** [comment]
I found the solution this way. It was something I missed because of IDE's autocomplete. I called the class from the wrong place.
look a images.

![Image](https://github.com/user-attachments/assets/4136b1e5-2071-445a-94d7-ec091d384f60)
![Image](https://github.com/user-attachments/assets/d16fee67-a98b-45b1-8a08-7d1d4ba6f247)

**Comment by jakecarlson** [comment]
> I found the solution this way. It was something I missed because of IDE's autocomplete. I called the class from the wrong place. look a images.

Thanks so much @veyselaydogdu, this was exactly my issue!
