### ISSUE TITLE
TextInput maxLength not working in Tabs

### ISSUE THREAD

**Issue by ewebsolution-dev** [laravel-filament/filament#11935]
### Package

filament/forms

### Package Version

v3.2.53

### Laravel Version

v10.48.3

### Livewire Version

v3.4.9

### PHP Version

PHP 8.2.3

### Problem description

```
return $form
->schema([
                Forms\Components\Tabs::make('Tabs')
                    ->tabs([
                        Forms\Components\Tabs\Tab::make('Tab-1')
                            ->label(__('Course information'))
                            ->schema([
                                Forms\Components\TextInput::make('title')
                                    ->label(__('Title'))
                                    ->maxLength(5)
                                    ->required(),
                            ]),
                    ]),
            ]);
    }
```
```
<input class="fi-input ..." id="data.title" type="text" wire:model="data.title">
```

### Expected behavior

```
<input class="fi-input ..." id="data.title" maxlength="5" required="required" type="text" wire:model="data.title">
```

### Steps to reproduce

```
return $form
->schema([
                Forms\Components\Tabs::make('Tabs')
                    ->tabs([
                        Forms\Components\Tabs\Tab::make('Tab-1')
                            ->label(__('Course information'))
                            ->schema([
                                Forms\Components\TextInput::make('title')
                                    ->label(__('Title'))
                                    ->maxLength(5)
                                    ->required(),
                            ]),
                    ]),
            ]);
    }
```

### Reproduction repository

https://github.com/ewebsolutions/filament-issue-input-length.git

**Comment by danharrin** [comment]
We are unable to use native HTML validation attributes within tabs because if a validation error is present in a tab that is not currently in view, the form will error out and not get submitted, and we have not found a way to automatically switch to the tab with the HTML validation error. The backend will still validate the max length upon submission.

Additionally, the same behaviour is present in the wizard and collapsible section components.

**Comment by ewebsolution-dev** [comment]
Thanks for the quick answer and the information about other components behavior. 
I will fix it with a piece of JavaScript to limit the number of characters that the user can input as a workaround the time to work on that.

**Comment by wdog** [comment]
have you tried a simple 

```php
->extraInputAttributes(['maxlength' => '5'])
```

**Comment by Adysone** [comment]
Hello,

I get the point for the "required" attribute because it's handled on submit, but the "maxlength" prevents the user from typing too many characters as the user types, not on submit.
It doesn't need to switch the tab or uncollapse section. Maybe it could be an exception?

There is the "problem" with <input type="email">, so maybe attributes can be added anyway?

**Comment by danharrin** [comment]
Only in certain browsers / OS does it limit the characters you can type, otherwise it shows an error when the user submits if the input is too long

**Comment by presidenwashil** [comment]
I've tried this approach to limit the number of digits while typing, and it works:
```php
    ->extraInputAttributes([
        'oninput' => "this.value = this.value.slice(0, 16);",
    ]);
