### ISSUE TITLE
try to import a file larger than 1MB, a validation error will occur.

### ISSUE THREAD

**Issue by bzy107** [laravel-filament/filament#12842]
### Package

filament/filament

### Package Version

v3.2.80

### Laravel Version

v11.7.0

### Livewire Version

v3.4.12

### PHP Version

PHP8.3.7

### Problem description

If you try to import a file larger than 1MB, a validation error occurs and the import fails. This is likely a validation error on the front end from Livewire or Filepond, but the exact cause is unclear.
This occurs when a file is selected or dragged and dropped.

![スクリーンショット 2024-05-18 0 12 17](https://github.com/filamentphp/filament/assets/28666304/398cb5a1-1f4d-4284-adb9-14fee1f704bc)

The importer has a feature to specify the maximum number of rows with `maxRows()`, but there is no feature to specify the file size. It would be very useful to have control similar to a `maxSize()` feature.

Please consider this.

### Expected behavior

Should be imported

### Steps to reproduce

On the /admin/patients screen, perform the import using ./storage/export-1-patients_over1M.csv.

Reproduction video:

https://github.com/filamentphp/filament/assets/28666304/6207545e-4b40-4d35-9764-ea2f566e3b13

### Reproduction repository

https://github.com/bzy107/filament-select-bug

**Comment by petrisorcraciun** [comment]
check config/livewire.php ->  temporary_file_upload -> 'max:...',

**Comment by bzy107** [comment]
> check config/livewire.php -> temporary_file_upload -> 'max:...',

I tried it, but it didn't work.
The same error occurs when the size exceeds 1MB. So, it seems to be caught by the validation before it even reaches livewire.php, but I don't understand the lifecycle well enough to pinpoint the exact issue.

when 'rules' => ['max:1024']:
![スクリーンショット 2024-05-21 19 48 52](https://github.com/filamentphp/filament/assets/28666304/5b76c90a-ee18-4779-beb8-64145f4f0d3e)

when 'rules' => ['max:1023']:
![スクリーンショット 2024-05-21 19 48 19](https://github.com/filamentphp/filament/assets/28666304/6482b3c8-129c-4ae7-a9b2-3dbdad2247b1)

**Comment by aSeriousDeveloper** [comment]
File Upload size validation is handled by the minSize and maxSize functions on the form component: https://filamentphp.com/docs/3.x/forms/fields/file-upload#file-size-validation

This is because FilePond, the JS package used for file uploads, has its own validation for file size that filament hooks into.

However, with the FileUpload component being baked into the Import Action, there's no easy way to modify these values yourself.

The max filesize should automatically be set to null if it isn't provided automatically, which would make me assume that any size would work. Can you check your `phpinfo();` for your `upload_max_filesize` ?

## Where values are set within the blade component

https://github.com/filamentphp/filament/blob/81949c0cdef974d3e57afd270f2dabd4f0da4cbe/packages/forms/resources/views/components/file-upload.blade.php#L72-L73

## Where the FileUpload component is made in the ImportAction

https://github.com/filamentphp/filament/blob/81949c0cdef974d3e57afd270f2dabd4f0da4cbe/packages/actions/src/Concerns/CanImportRecords.php#L80-L83

**Comment by bzy107** [comment]
Thank you for your reply. I have already checked the same points.

Since `$getMinSize` in FilePond is not set, it should be null.
`upload_max_filesize` is also set to 2MB, so that’s not the issue.
Therefore, I’m stuck.

**Comment by bzy107** [comment]
So, does this mean that currently in the importer, we can't set `minSize()` and `maxSize()`, so we should add methods for them?
I need to investigate a bit more.

**Comment by bzy107** [comment]
Progress Update:

I modified the CanImportRecords.php file to add `maxSize()`, but it didn't work. Further investigation is needed.

maxSize set 100MB:
![スクリーンショット 2024-05-22 1 14 47](https://github.com/filamentphp/filament/assets/28666304/fe8a9d0c-990e-4903-abbf-30664c641658)
![スクリーンショット 2024-05-22 1 16 27](https://github.com/filamentphp/filament/assets/28666304/c0447944-bbde-4131-8b7c-c6273adc1321)

**Comment by bzy107** [comment]
I found the cause.
It was not on the Filament side but on the Nginx side, where I overlooked a 413 Request Entity Too Large error.
![スクリーンショット 2024-05-22 1 37 37](https://github.com/filamentphp/filament/assets/28666304/e35ab7a7-f5ed-4117-abbe-6a2c033869a6)

I resolved it by adding the `client_max_body_size` setting.
```bash
server {
    client_max_body_size 10M;
    ....
```

I hope this helps anyone who encounters the same issue.
