### ISSUE TITLE
Table widget on dashboard - $columnSpan = 'full' does't take affect

### ISSUE THREAD

**Issue by TheSoulrester** [laravel-filament/filament#14579]
### Package

filament/widgets

### Package Version

v3.2

### Laravel Version

v11.9

### Livewire Version

3.4

### PHP Version

8.2

### Problem description

I had a single table widget showing on my default dashboard. I changed the column width with `protected int|string|array $columnSpan = 'full';` successful to the full width.

Then, I implemented a custom blade-Template because I wanted to have Tabs in my widget. 

Now, the widget only appears in a one column width. Not in full width anymore.
<img width="1470" alt="Bildschirmfoto 2024-10-20 um 12 10 38" src="https://github.com/user-attachments/assets/7b859bbc-a1c6-4d81-97d5-fb3d32192e82">

I still have the columnspan = "full" in my code: https://github.com/Feuerwehr-Bamberg-Loschgruppe-1/Strichliste/blob/b2d8132dd83d2546ae642574fe448a61288f9d24/app/Filament/Widgets/MonthlyDrinksWidget.php#L17

### Expected behavior

I expected that the widget would be rendered in the fulll width.

### Steps to reproduce

Create a table widget and set it to full width.
The widget appears in full width.
Now add the public function render() and set the view to a custom blade-template
Now, the widget appears as a one column widget and not in full width anymore.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Feuerwehr-Bamberg-Loschgruppe-1/Strichliste

**Comment by TheSoulrester** [comment]
Without public function render()
<img width="1470" alt="Bildschirmfoto 2024-10-20 um 12 18 05" src="https://github.com/user-attachments/assets/88541ece-6637-495c-b5f4-145a030bb85c">

**Comment by TheSoulrester** [comment]
I found the solution. A user give me the hint that I had to change the div to 
`<x-filament-widgets::widget>
///
</x-filament-widgets::widget>`

But I didn't found this in the table widget part neither in the widget blade template.

**Comment by sylann** [comment]
In case it helps someone else, this problem still exists.

It is caused by incorrect combinations of `Dashboard->getColumns()` and `Widget->columnSpan`.
These may produce incorrect combinations of underlying CSS properties (`grid-template-columns` on the grid container, and `grid-column` on child elements). (EDIT: forgot to mention `grid-auto-columns`)

**To fix the issue**, you should make sure that all the widgets of a Dashboard use a correct value for `Widget->columnSpan`.
- so, either `'full'`
- or an integer between `1` and `Dashboard->getColumns()` (included)
  - with the base dashboard you can only use `1` or `2` (NOT ~~`1` to `12`~~, see below)

It works all the same when using an associative array of breakpoint to value.
In this case, each value of the array must be correct.

---

I think the maintainers should probably address this:

The documentation mentions [here](https://filamentphp.com/docs/3.x/panels/dashboard#customizing-widget-width) (emphasis mine):

> You may customize the width of a widget using the $columnSpan property. **You may use a number between 1 and 12** to indicate how many columns the widget should span, or full to make it occupy the full width of the page:

I think it's fair to expect this section of the documentation to mention that you should think of what value is returned by the `getColumns` method of the parent `Dashboard`.

Also, the base `Filament\Pages\Dashboard->getColumns` method returns `2` instead of `12`.
There could be a good reason for returning 2, that I don't know of... but 12 is:
1. the common number of columns in a design system
2. the max value used by filament in general
3. the max value indicated in the documentation above

Hope this helps.
