### ISSUE TITLE
unique() validation of TextInput field ignores dehydrateStateUsing()

### ISSUE THREAD

**Issue by nxu** [laravel-filament/filament#14594]
### Package

filament/filament

### Package Version

v3.2.95

### Laravel Version

v10.48.16

### Livewire Version

v3.5.4

### PHP Version

PHP 8.2.22

### Problem description

As reported in #10650 :

- TextInput field 
- dehydrateStateUsing()
- unique()

The `unique()` validation happens before `dehydrateStateUsing()` is being ran. If a field is transformed and the resulting new string is not unique in a database field with a `unique` index, a DB error is thrown. 

### Expected behavior

I would expect the `unique()` validation rule to be ran **after** the transformation by `dehydrateStateUsing` has happened.

### Steps to reproduce

- Create a `TextInput` field with `dehydrateStateUsing()` and `unique()`
- Submit the form

Reproducing in the example repo:
- Create a new test entry with string '_test'
- Create another new test entry with the same value ('_test')

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/nxu/filament-bug

**Comment by danharrin** [comment]
Correct, the dehydration process happens after the validation process, this is by design. Fields that are not dehydrated still need to be validated. Please use a help forum to ask the best solution to move forward with your problem, as I don't really know what you're trying to do here. You may need to use a custom rule.

**Comment by rvarjao** [comment]
I have the same problem. Someone could find a solution?

Steps:
I created a custom field called CPF that the values are for example: 123.456.789-01. But I'm saving it as 12345678901. When create another one, the form validate an unique value with dots and dash, so it's a valid value, but when try to save (only digits) it throws an exception because the value (only digits) already have in database.
