### ISSUE TITLE
Dark overlay appears when clicked on modals

### ISSUE THREAD

**Issue by PrasadChinwal** [laravel-filament/filament#15017]
### Package

filament/filament

### Package Version

v3.2.57

### Laravel Version

v11.34

### PHP Version

8.2

### Problem description

I have an action button with forms and when clicked it shows a dark overlay. I am unable to close the overlay but when refreshed it goes away. 

<img width="1512" alt="Screenshot 2024-12-06 at 1 16 56 PM" src="https://github.com/user-attachments/assets/99c785a9-b250-4454-b9cf-dbb7295c9fef">

<img width="1511" alt="Screenshot 2024-12-06 at 1 11 37 PM" src="https://github.com/user-attachments/assets/9839db9f-95a8-47f8-91f0-d1ae42cf3f48">

### Expected behavior

It opens a modal with form without overlay.

### Steps to reproduce

- clone the repo
- Run 
```bash
composer install && npm install && npm run build

cp .env.example .env
php artisan key:generate
php artisan migrate
```

Visit the application, register user and login.

Go to the users resource and click on the `Create User from AD` button.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/PrasadChinwal/filament-overlay-issue

**Comment by PrasadChinwal** [comment]
P.S. If you try to show a hide or show column on Users table the issue is the same.

**Comment by navasssss** [comment]
It also appears when interacting with toggles. - ( My project is stuck with this issue. I hope you can provide a quick and effective solution, or is there a way to change the version and resolve the issue? )

**Comment by abbasmashaddy72** [comment]
Hi @navasssss, 

It seems the issue might be caused by `spatie/laravel-support-bubble`, which uses Tailwind CSS version 2. To resolve this, try temporarily removing its configuration from your Tailwind CSS config file and test again.

You can remove or comment out the following lines in your `tailwind.config.js` file:

```javascript
'./vendor/spatie/laravel-support-bubble/config/**/*.php',
'./vendor/spatie/laravel-support-bubble/resources/views/**/*.blade.php',
```

For more details, you can refer to the package's documentation here: [[spatie/laravel-support-bubble](https://github.com/spatie/laravel-support-bubble#readme)](https://github.com/spatie/laravel-support-bubble#readme).

Let me know if this helps resolve the issue! 😊

**Comment by PrasadChinwal** [comment]
@abbasmashaddy72 I tried, removing the `spatie/laravel-support-bubble` package but the issue still persists. I have used this in a previous project along with Filament 3 without any issues. I just updated my reproduction repo without the `spatie/laravel-support-bubble` package.

**Comment by xKishon** [comment]
I have the same problem, still no solution...any idea?

**Comment by xKishon** [comment]
I managed to resolve the issue.

In my case, the problem was caused by a plugin that automatically updated Livewire to version 3.5.16. This update introduced the issue with the modal backdrop.

To fix it, I forced Livewire to revert to version 3.5.12 by editing my composer.json file and
`"livewire/livewire": "3.5.12"`

Then, I ran the following command to apply the change:
`composer update livewire/livewire`

After downgrading Livewire, the issue was resolved, and everything works as expected again.

**Comment by mckenziearts** [comment]
Yes, it worked for me too, it's a temporary solution I think.  Thank @xKishon

**Comment by Alldhow03** [comment]
I also have the same problem. I have downgraded my livewire to version 3.5.12, but the problem still persists. @xKishon

**Comment by GabrielSieben** [comment]
I ran into this on Filament Tables on the frontend site - any interaction would trigger it. Baffling.

**Comment by karlgray** [comment]
@xKishon Thank you so much. I have been fighting this since last night.   I couldn't understand it as this was a fresh install of Laravel and Filament with no add ons or extensions or any changes at all.  I simply ran the migration and did a resource --simple.  Broken out of the box and very frustrating for someone new to Laravel.

**Comment by barimess** [comment]
As someone who is quite new to laravel as a whole and filament in particular I have had this issue all night, if I try to use the search functionality the black modal shows up and if I try to sort by `created_at` or `updated_at` same thing happens. 
Hope this is resolved soon I should mention I installed filament "3.2.66" since the default "^3.2" didn't seem to work. Will try downgrading the livewire version tomorrow and hope this works

**Comment by danharrin** [comment]
As above, a Livewire update broke this and Filament locked the version down, but if you had already updated you wouldn't be able to get it if another package requires it higher.

**Comment by khalilKhassep** [comment]
This happens due to a Livewire state change, which causes the component to re-mount. The strange thing is that it triggers all modals, even though they are strictly conditioned to check for each mounted action.

**Comment by MansourM** [comment]
Hello
this issue seems to have re appeared in some way, have not discovered why, but in prod server when i click the action dark overlay will cover the screen but on local it is fine
* tested reverting back to 3.5.12
* updating to latest versions

non worked

------------
edit: updating everything fixed it at some point

**Comment by olivsinz** [comment]
I found a way to fix it. 

Instead of running:
```
composer require filament/filament:"^3.2" -W
```

run: 

```
composer require filament/filament -W
```

It will install filament 3.3 with some update. Livewire 3.6 also.

Inspired by: https://stackoverflow.com/a/79272083/9131185

**Comment by SteJaySulli** [comment]
I have this issue without any overridden views. I did spot that there seem to have been a bunch of changes to javascript files that I don't recognise, should have thought more of it at the time but didn't. Downgrading Livewire seems to have fixed the immediate issue (Thanks @xKishon) but it's not ideal.

**Comment by informatJonas** [comment]
Can the bug also be fixed in L12?

**Comment by informatJonas** [comment]
@danharrin pls reopen

**Comment by danharrin** [comment]
If you have issues with this its probably to do with outdated Filament JS assets, check your caches etc

**Comment by informatJonas** [comment]
I updated everything just now.

**Comment by informatJonas** [comment]
Could it possibly be related to filament?

**Comment by danharrin** [comment]
Please create a reproduction repository

**Comment by informatJonas** [comment]
I have now used a completely fresh installation of L12 + filament, everything works there. So it must have something to do with caches. I'll try to move it to the original repo in the next few days. Otherwise we'll just have to move everything into the fresh installation.

**Comment by danharrin** [comment]
Specifically, the `support.js` file being out of date will cause the problem

**Comment by rauldotgit** [comment]
> If you have issues with this its probably to do with outdated Filament JS assets, check your caches etc

The overlay happened to me after a change to a newer branch and a composer install - clearing all caches has solved it. Thanks!

**Comment by laze** [comment]
Still... I have the same issue...

Versions:
- Filament v3.3.31  
- Livewire v3.6.4 

It shouldn't be cached items, because it's a freshly generated Docker container.

**Comment by mhsaghatforoush** [comment]
thanks @xKishon
