### ISSUE TITLE
Belongs to Many: Prevent Attaching already Attached Model

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#1804]
### Discussed in https://github.com/laravel-filament/filament/discussions/1510

Due to laravel/framework#4962, belongs to many relation managers have unexpected behaviour when dealing with multiple relationships between the same 2 Eloquent records.
- Detaching one instance detaches all.
- Editing pivot data does not work except for the first instance.

<div type='discussions-op-text'>

<sup>Originally posted by **intrepidws** February  8, 2022</sup>
I have a Belongs to Many relationship between Registrants and Codes. I have a `CodesRelationManager` class (which extends `BelongsToManyRelationManager`) and am using that to allow codes to be attached to registrants. Currently, there is nothing to prevent someone from attaching a code to a registrant if that code is already attached to the registrant. Is there a way to prevent this?

I have the following code for my `attachForm` method:

```
public static function attachForm(Form $form): Form
{
    return $form
        ->schema([
            static::getAttachFormRecordSelect()
                ->searchable(['code', 'type', 'title']),
            Forms\Components\Select::make('quantity')
                ->required()
                ->options(array_combine(range(1, 100), range(1, 100)))
                ->default(1),
        ]);
}
```</div>

**Comment by kamilst96** [comment]
Since this is already open, and seems related to my issue, I'll put it here.
I have belongsToMany relationship like shown below:

```
User:
- id

Location:
- id
- date_from
- date_to
- is_active

LocationUser:
- pivot_id
- location_id
- user_id
- pivot_date_from
- pivot_date_to
- pivot_is_active
```

Since User can be assigned to location A, move to location B, then return back to location A, I expect this information to be retained. For this, I added `pivot_id` to `location_user` and fetch `LocationUser` model in my actions, completely bypassing Laravel's attach/detach feature.

My problem now is with how Filament identifies unique records in RelationManager. If I have multiple records with the same subject and owner, it will select them all. If I edit one pivot, it will show one of them no matter which I click.

Is it possible to convince RelationManager to use specific key as index for tables and actions?

Maybe an override of this kind would be an option:
`protected string|array $identifyRelationBy = 'pivot_id'`
