### ISSUE TITLE
Avatar component does not accept a full image URL

### ISSUE THREAD

**Issue by Gummibeer** [laravel-filament/filament#242]
**Describe the bug**
If `\App\Models\User::getFilamentAvatar()` return s a full URL - for example a Gravatar, Unavatar or similar service URL - the avatar blade component prepends the already absolute URL with the app URL.

**Expected behavior**
It should render the `<img/>` tag with the given full URL.

**Screenshots**
<img width="1087" alt="Bildschirmfoto 2021-03-18 um 17 50 33" src="https://user-images.githubusercontent.com/6187884/111664831-78a80c00-8812-11eb-80da-4906defaa9fa.png">

**Fix**

Add another condition to the `\Filament\View\Components\Avatar::src()` method.

```php
if (Str::startsWith($avatar, ['http://', 'https://'])) {
    return $avatar;
}
```

**Comment by kurucu** [comment]
In a roundabout way, I found this for the wrong reasons. So just in case anybody else does.

I assumed the http / https check was failing for some reason (especially because the docs don't mention it for ImageColumn, the stacked() feature being a masterpiece, by the way).

But that was not the case. You must extend `Filament\Models\Contracts\HasAvatar` with your user model for it to detect and use `getFilamentAvatarUrl()` in e.g. the ImageColumn.

For others who've found it here, the reason you might want to do this is because you've delegated avatars to your social auth, and it's just a full-URL property on your model by the time your app or Filament gets to it. My model has an attribute getter, which looks for it and provides a custom default if it doesn't exist. Don't forget to append that to your model too.
