### ISSUE TITLE
Possible bugfix with translation system

### ISSUE THREAD

**Issue by tonyyb** [laravel-filament/filament#474]
**Describe the bug**

First of all, thanks for this package : it's very awesome and easy to use !

There is a possible bug with translations usage. 
If a Laravel translation file has the same name of a ressource, we have an exception : 

```
htmlspecialchars() expects parameter 1 to be string, array given
``` 

Example of call in filament : https://github.com/laravel-filament/filament/blob/main/resources/views/components/nav-link.blade.php#L14

There are several calls with the same logic in the code. 

**To reproduce**
1. Create a `lang/en/galleries.php` trans file with following return (standard comportment) : 

```php
<?php

return [];
```

2. Create a `Gallery`resource 

3. Navigate to admin part : error will be triggered.

**Expected behavior**

I think the trans call should not be called from blade view. 
We already have methods to override label and title (ex: `getLabel()`) so why doing several time thinks without control ? 

**Screenshots**

**Context**
- Package version: 4.4.1
- Livewire version: 2.5.1
- Laravel version: 8.49.0
- PHP version: 7.4
- Database: Mysql 5.7

**Comment by danharrin** [comment]
Hey! Thanks for your kind words and bug report. I can see why this behaviour could be irritating, but removing translation support from nav items would be a breaking change that we cannot make in v1. Personally, I think that the benefits of having translatable navigation items greatly outweigh the negatives, but I am welcome to feedback in this thread from the rest of the community if you have had this same issue - I may change my mind.

A fix you could try for this issue is overriding the `$navigationLabel` property on your model to be a custom translation string in your app, for example:

```php
public static $navigationLabel = 'filament.nav.galleries';
```

Let me know if this works!
