### ISSUE TITLE
`Tables\Actions\CreateAction` creates a record in DB instaed of opening a Modal

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-filament/filament#4900]
### Package

filament/filament

### Package Version

v2.16.45

### Laravel Version

9.39.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.10

### Problem description

When I add `Tables\Actions\CreateAction` in the header actions of table and click on the button to open a `Modal (form)` for creating a record it is trying to add entry into database instead of opening a model.

### Expected behavior

It should open a Modal for creating/editing

### Steps to reproduce

1. Setup a project locally
2. login using following credentials (`admin@admin.com` / `password`)
3. Navigate to `Users` menu
4. Click on `Button without issue` This will open a model and you can create a user (Working Fine)
5. Click on `Button with bug` This will try to create a new user in table Instead of getting the data from form (This action will fail because field `name` is not marked as nullable in migration)

### Reproduction repository

https://github.com/ManojKiranA/filament-simple-modal-resource

**Comment by danharrin** [comment]
Pass in the `->form()`

**Comment by ManojKiranA** [comment]
How come this works properly on relation manager header actions but no in mamage records

**Comment by danharrin** [comment]
Because we explicitly pass the form to certain actions that we pre-define, the rest you do yourself. The table actions arent aware that the resource even exists unless we tell them.

**Comment by ManojKiranA** [comment]
So you are telling me that if I move the form schema from resource to `ManageRecord` class that will works just fine. Is that what you are trying to tell

**Comment by danharrin** [comment]
if you use a Create page action instead of a Create table action in the reccomended place then it works out of the box

but we havent anticipated that people use a table action for this outside of the relation manager. so the relation manager is the only class that automatically passes the form to the Create action at the moment.

for example, this is how we pass the form to the edit action on the list / manage page - https://github.com/filamentphp/filament/blob/2.x/packages/admin/src/Resources/Pages/ListRecords.php#L251-L262

**Comment by ManojKiranA** [comment]
Thanks for your explanation. Now I get it
