### ISSUE TITLE
Eagerload query get replaced by Filament

### ISSUE THREAD

**Issue by rahmanramsi** [laravel-filament/filament#5489]
### Package

filament/tables

### Package Version

v2.16.62

### Laravel Version

v9.48.0

### Livewire Version

v2.11.0

### PHP Version

PHP 8.1.14

### Problem description

When manually eager load a relation
```php
    protected function getTableQuery(): Builder
    {
        return Post::query()
            ->with([
                'author' => fn ($query) => $query->withTrashed()
            ]);
    }
```

And then show it on column
```php
Tables\Columns\TextColumn::make('author.name')
```

A relation that manually eager load before get replaced by Filament.

Author relation with trashed get retrieved
![image](https://user-images.githubusercontent.com/48276043/213110311-7f166506-6483-4983-9726-d1bd58ec7e69.png)

### Expected behavior

Author relation with trashed get retrieved

![image](https://user-images.githubusercontent.com/48276043/213110074-42bb4751-020a-472d-97e8-5bc0ab32e5f6.png)

### Steps to reproduce

1. Clone repo
2. Migrate everything
3. Serve laravel

### Reproduction repository

https://github.com/rahmanramsi/filament-eagerload

**Comment by danharrin** [comment]
Thanks for the issue! But I don't think it's something "wrong" with Filament, because this is how Eloquent behaves when you try to eagle-load something twice. Not really something we can fix in our own code.

However, I understand why `withTrashed()` would be useful. So I propose that you add a `scopeRelationshipUsing()` method to the Column which could enable this behaviour by accepting a `$query` callback. A PR would be great!
