### ISSUE TITLE
Select's placeholder disappears when updated by another select

### ISSUE THREAD

**Issue by antoinemy** [laravel-filament/filament#6736]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v10.13.5

### PHP Version

8.1.14

### Problem description

The "Select an option" placeholder disappears completely when we reset it with the `$set('myComponent', null);` method in `afterStateUpdated()`

This problem comes particularly from the `searchable()` method present on the select.

https://github.com/filamentphp/filament/assets/9550130/9f5024ad-06a0-46c0-990f-5fe4763c6f68

### Expected behavior

After the component is reset by `$set('myComponent', null);`, I would like the component to return to the original value of the placeholder: "Select an option" as it does when we click on the cross in the select. For now, it remains worthless.

### Steps to reproduce

- Create a form on a resource
- Add the following code:
```
Select::make('test')
    ->options([
        'Option #1',
        'Option #2',
    ])
    ->reactive()
    ->afterStateUpdated(function(Closure $set) {
        $set('test-updated', null);
    }),
    
Select::make('test-updated')
    ->searchable()
    ->options([
        'Option Test #1',
        'Option Test #2',
    ]),
```
- Observe the value of the placeholder of the select 'Test Updated' when you change the value of the select 'Test'

OR 

You can reproduce the attached deposit on the form of the 'User' resource

### Reproduction repository

https://github.com/antoinemy/filament_bug_disappear_placeholder

**Comment by archilex** [comment]
I believe the problem lies in `watch` method. `this.refreshPlaceholder()` is called at the beginnging of the watch, but then `this.select.clearStore()` is called which removes the placeholder. Adding `this.refreshPlaceholder()` after `this.select.clearStore()` fixes this issue. 

You can test this by just removing `clearStore()` and the placeholder will show. I'm sure `clearStore` is needed so the easiest option seems to be to refresh the placholder after calling `clearStore()`.
