### ISSUE TITLE
Fix infolists and forms tabs when hiding a tab after Livewire request

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#6962]

**Comment by danharrin** [comment]
@zepfietje Please provide a reproduction repo

**Comment by zepfietje** [comment]
Repo: https://github.com/zepfietje/filament-issue-6962
Issue commit: https://github.com/zepfietje/filament-issue-6962/commit/4b9b0575a7ad1cb78ea624cbaa0f23a4ace56345

1. Clone
2. Composer install
3. `php artisan key:generate`
4. `php artisan migrate`
5. `php artisan db:seed`
6. Go to `http://filament-issue-6962.test/admin/users/1`
7. Trigger the "Hide first tab" action to update the user's name
8. First tab hides, since it only shows for original name
9. Second tab is active, but it's content is not shown
10. Reload the page to have the tab content load correctly
