### ISSUE TITLE
Native date time picker placeholder color is wrong in Safari

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7087]
https://github.com/tailwindlabs/tailwindcss-forms/issues/38

**Comment by nathanheffley** [comment]
This issue seems to be recurring in v4, where the placeholder color is far too dark in light mode on Safari. These are two date inputs, one with a value selected and one with no value.

<img width="823" height="93" alt="Image" src="https://github.com/user-attachments/assets/e6ff39a1-8f6b-4f5b-ab38-8507d456bfd9" />
