### ISSUE TITLE
Preload on select, do too much requests

### ISSUE THREAD

**Issue by sbc640964** [laravel-filament/filament#7251]
### Package

filament/filament

### Package Version

3.0.0-beta17

### Laravel Version

10.16.1

### Livewire Version

3.0.0-beta4

### PHP Version

8.2.3

### Problem description

When I use Select input with search and preload relations records
The input requests the records on each opening of the dropdown.

It's completely unnecessary, how can you not repeat the loading again.

### Expected behavior

The selection input will prompt for the data once when opening the dropdown for the first time.
On the second opening onwards, it will be retrieved from the first request and will not cause unnecessary performance

### Steps to reproduce

use Select Input in form

```
Forms\Components\Select::make('customer_id')
         ->relationship('customer', 'name')
         ->searchable()
         ->preload()
```

### Reproduction repository

https://github.com/filamentphp/filament/issues/7251

**Comment by sbc640964** [comment]
Oh, it's something very simple and clear, I don't think I need to create a repository

**Comment by danharrin** [comment]
No, all issues require a repository, no matter how simple you think they are.

And this is intended behaviour, select options can be dynamic based on other fields, and this ensures that the options are up-to-date.

**Comment by woboti** [comment]
Apologies for necroposting, but I want to leave this here, in case anyone needs it.
The issue is that the values preloaded on render are not reused when you focus on the select again, with fresh values being fetched from the backend every time.
Here's a quick, hacky, and maybe very dirty workaround:
```php
       Select::make('field_name')
                ->relationship('relationship_name')
                ->viewData(function(){
                    return ['getOptionsForJs' => fn() => []];
                })
                ->preload()
```
Another, more elegant solution, is copying the component view to the resources\views\vendor\filament-forms\components folder and changing
```js
options: @js($getOptionsForJs())
```
to something along the lines of:
```js
options: @js($hasDynamicOptions() ? [] : $getOptionsForJs()),
```
