### ISSUE TITLE
TextEntry::make()->placeholder('-'); not working for nullable columns

### ISSUE THREAD

**Issue by CodeWithDennis** [laravel-filament/filament#7401]
### Package

filament/filament

### Package Version

v3.0.3

### Laravel Version

v10.10

### PHP Version

PHP 8.2

### Problem description

```PHP
TextEntry::make('name')->placeholder('-'),
```

When the column is `null` it won't trigger the placeholder

### Expected behavior

The placeholder should show in this case: `-`

### Steps to reproduce

Add a `TextEntry::make('column_name_here')->placeholder('-')` with a column that currently has a `null` value.

**Comment by ashleyhood** [comment]
@zepfietje I can confirm that this is an issue.

The problem is in the view when looping through the data:

https://github.com/filamentphp/filament/blob/41897f7f56035a714d8753cf7ea775eb1d5b4709/packages/tables/resources/views/columns/text-column.blade.php#L64

Since the array will be empty, it will skip the `foreach` loop.

A possible solution is after:

https://github.com/filamentphp/filament/blob/41897f7f56035a714d8753cf7ea775eb1d5b4709/packages/tables/resources/views/columns/text-column.blade.php#L38

add the following code:

```PHP
if (blank($arrayState) && filled($placeholder)) {
    $arrayState = \Illuminate\Support\Arr::prepend($arrayState, '');
}
```

A work around is to use `->default` on the TextColumn instead of `->placeholder`.

**Comment by danharrin** [comment]
@ashleyhood can you make a PR then please?
