### ISSUE TITLE
CreateAction in headerActions "mutateFormDataUsing" method doesn't work in RelationManager table

### ISSUE THREAD

**Issue by guilebc** [laravel-filament/filament#7547]
### Package

filament/filament

### Package Version

v3.0.12

### Laravel Version

v10.17.1

### Livewire Version

v3.0.0-beta.7

### PHP Version

PHP 8.2.8

### Problem description

I'm in a RelationManager, I want to add a CreateAction::make() button in "headerActions" at the "table" method.
I also use "spatie-laravel-translatable-plugin".

The following code below (cf. screenshot) does not work. The "mutateFormDataUsing" method for modifying the data on save is not taken into account.
https://cdn.discordapp.com/attachments/1138411483835936779/1138411484423135312/image.png

Even when I put a "dd" my code is not interrupted. It's as if this method really wasn't called.

https://filamentphp.com/docs/3.x/actions/prebuilt-actions/create#customizing-data-before-saving

### Expected behavior

That the modifications are taken into account before being saved in the database.

### Steps to reproduce

Install package: https://github.com/filamentphp/spatie-laravel-translatable-plugin with minimal configuration (https://github.com/filamentphp/spatie-laravel-translatable-plugin#translating-relation-managers).

```
Tables\Actions\CreateAction::make()
    ->mutateFormDataUsing(function (array $data): array {
        // This is the test.
        $data['video_attachment'] = 'https://google.com';
        return $data;
    }),
```

### Reproduction repository

https://gist.github.com/guilebc/b46f7cb7aedab300b8a7062b2f232629

**Comment by adriaardila** [comment]
Having the same issue in a custom page inside the getHeaderActions method:


Actions\CreateAction::make('location')
                ->label('New Location')
                ->color('secondary')
                ->model(EventSessionsLocation::class)
                ->form(EventSessionsLocationResource::getFormFields())
                ->mutateFormDataUsing(function (array $data): array {
                    $data['event_id'] = $this->event->id;
                    return $data;
                })

The mutateFormDateUsing method does nothing

**Comment by MuhammadKazimSadiq** [comment]
having same issue...anyone found a solution?

**Comment by guilebc** [comment]
> having same issue...anyone found a solution?

I currently use an Observer to intercept the model before it is saved.
I focused on the "saving" event.
> The saving / saved events will dispatch when a model is created or updated

More info here: https://laravel.com/docs/10.x/eloquent#observers

**Comment by lamberttraccard** [comment]
I had the same issue, something is going wrong when using the same action in the emptyStateActions as well, passing a dedicated key to the ->make() method should resolve the problem. 

```php
 ->headerActions([
                Tables\Actions\CreateAction::make('header')
                    ->mutateFormDataUsing(function (array $data): array {
                        // This is the test.
                        $data['video_attachment'] = 'https://google.com';
                        return $data;
                    }),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make('empty'),
            ]);
```

Even better maybe use the same action instance for both, which should make sens, since you probably want the same behaviour in the emptyStateActin as well.

**Comment by lamberttraccard** [comment]
Related to https://github.com/filamentphp/filament/issues/7649

**Comment by zepfietje** [comment]
All actions inside a Livewire component should have a unique name.
Since you're using `CreateAction` twice (header and empty state), modifications to the header action don't actually work, since the empty state action get's triggered (because of the duplicate name, as `CreateAction` instances have a default name of `create`).

This isn't a bug, though I understand it's confusing when you encounter it at first.
So, make sure to pass a unique name if you're using multiple instances of prebuilt actions on a single Livewire component.

Just checking if @danharrin agrees, or we can come up with a way to improve the DX here.
