### ISSUE TITLE
Pagination overlaps page selector on mobile

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#7597]
![image](https://github.com/filamentphp/filament/assets/41773797/ec8be46a-cf4e-47cc-95ff-b9781c8e2f92)

**Comment by zepfietje** [comment]
On mobile the simple pagination UI is used though:

<img width="373" alt="Screenshot 2023-08-10 at 09 06 22" src="https://github.com/filamentphp/filament/assets/44533235/9d2f117b-4b48-44b6-9671-409823a7103e">

However, the issue does occur when having a lot of pages on `>= md` screens.
It's tricky as the styling depends on the screen breakpoint, which makes the issue occur on larger screens (while not on smaller screens) if there's an open sidebar:

<img width="1071" alt="Screenshot 2023-08-10 at 09 10 51" src="https://github.com/filamentphp/filament/assets/44533235/83f6dba7-2ef7-4bbf-a584-4d3884cd79a1">

To account for this, we'd have to get rid of the page selector entirely, which also isn't a good solution as it degrades the UX in more cases. Maybe we should start using container queries already: https://caniuse.com/css-container-queries.

**Comment by danharrin** [comment]
Yeah, lets go with container queries here

**Comment by mauricekindermann** [comment]
Happens on desktop with large datasets, especially when on the the back-end of the results:

<img width="948" alt="image" src="https://github.com/filamentphp/filament/assets/3828998/a8d7af26-a38b-472a-a22d-12fa3a4d023c">

<img width="939" alt="image" src="https://github.com/filamentphp/filament/assets/3828998/306f095a-0711-4b22-a332-9f3bfee8ab48">

And as the screen shrinks, it obscures more

<img width="397" alt="image" src="https://github.com/filamentphp/filament/assets/3828998/86932727-f83c-43fe-84bf-03b3d530ef77">

One solution when doing container queries might be to have heirachy, preferring something like this when space is limited: 

```
< [first] ... last >
< first ... [last] >
< first ... [X] ... last >
```

Which would shrink it down to this. No functionality is lost since the arrows always allow for next/previous. If anything it visually simplifies where you are. 

<img width="951" alt="image" src="https://github.com/filamentphp/filament/assets/3828998/a67ba537-0f60-4a8c-af26-c2e40f3f51ad">

**Comment by zepfietje** [comment]
https://github.com/filamentphp/filament/pull/8447#issuecomment-1721054022

**Comment by zepfietje** [comment]
@danharrin, can we even add the container queries Tailwind CSS plugin as a non-breaking change? This would require devs who manually compile their stylesheets to add the dependency, right? Or could we add it in a backward-compatible way by falling back to the current screen breakpoints (if that doesn't collide with the container breakpoints)?

**Comment by danharrin** [comment]
I'd want to fall back to the screen breakpoints anyway, otherwise it might break some old browsers

**Comment by zepfietje** [comment]
Yeah, will have to check if we can make it work with `supports-` maybe.

**Comment by danharrin** [comment]
Or write custom CSS without TW and bundle it with the asset system, that wouldn't be a breaking change

**Comment by valpuia** [comment]
What about this? https://laravel.com/docs/10.x/pagination#adjusting-the-pagination-link-window and provide `onEachSide(1)`

**Comment by zepfietje** [comment]
That would degrade the UX on large screens too.

**Comment by zepfietje** [comment]
> What about this? https://laravel.com/docs/10.x/pagination#adjusting-the-pagination-link-window and provide `onEachSide(1)`

Just for context: this seems to be the default already, but doesn't do exactly what you think it does.
