### ISSUE TITLE
Column styling with some extraAttributes and/or url attr doesn't change

### ISSUE THREAD

**Issue by anatolyeltsov** [laravel-filament/filament#7616]
### Package

filament/filament

### Package Version

v3.0.15

### Laravel Version

v10.18.0

### Livewire Version

v3.0-beta

### PHP Version

PHP 8.1.7

### Problem description

1. If you try to add some text-color Tailwind classes in [extraAttributes](https://filamentphp.com/docs/3.x/tables/columns/getting-started#custom-attributes) to column they wouldn't work as in Filament v2 because they're overlapped by classes from fi-ta-text-item element
![Screenshot from 2023-08-09 22-39-06](https://github.com/filamentphp/filament/assets/54027342/a43332d2-478a-4a44-abb1-65e3674d3e18)
2. If you add [url attribute](https://filamentphp.com/docs/3.x/tables/columns/getting-started#column-actions-and-urls) to column it will be styled the same as non-link column (in Filament v2 it had a primary color) - only text-decoration changes on focus and this may be not the best for UX

Both can (or should I say can't :D) be seen on this screenshot (and the same for dark theme):
![Screenshot from 2023-08-09 22-42-30](https://github.com/filamentphp/filament/assets/54027342/1d5e9eee-00fc-42e7-ac9b-031b8f0200ba)

### Expected behavior

1. Column uses all of it's extraAttributes correctly
2. Column with url attribute is styled differently to standard column

### Steps to reproduce

1. Create any resource
2. Add some columns
3. Add url and extraAttributes attrs

### Reproduction repository

https://github.com/anatolyeltsov/filament/tree/column-extra-attributes-and-urls

**Comment by zepfietje** [comment]
These changes are by design and not bugs in my opinion. Here's why and how to achieve the behavior you want:

1. Since text columns allow array state now (list of items), each item can have a different color configured based on its state. You should target `[&_fi-ta-text-item]` or similar using Tailwind CSS. However, in your reproduction repo you're just setting the text to gray, which can simply be achieved by `color('gray')` on the column instead.
2. Adding a URL to a text column only adds an underline since the colors etc. can be configured separately. If it's more desirable that the actual link component is used under the hood, I'm open for discussion or a PR.
