### ISSUE TITLE
the hidden and visible methods not working in NavigationItem

### ISSUE THREAD

**Issue by gasner** [laravel-filament/filament#7769]
### Package

filament/filament

### Package Version

3.0.21

### Laravel Version

10.10

### Livewire Version

3

### PHP Version

8.1

### Problem description

Even though I mark that they should not appear in the navigation, they still do. 
```php
NavigationItem::make('Add Passengers')
                    ->url(fn()=>...)
                    ->hidden(fn(): bool => true)
```
There is no effect.

### Expected behavior

Navigation Item should not appear.

### Steps to reproduce

```php
NavigationItem::make('Add Passengers')
                    ->url(fn()=>...)
                    ->hidden(fn(): bool => true)
```

### Reproduction repository

https://github.com

**Comment by adampatterson** [comment]
Same with Filament 2

**Comment by sfz305** [comment]
I'm seeing the same. I suspect its due to this function ignoring anything set on hidden or visible:
vendor/filament/filament/src/Pages/Page.php

public static function getNavigationItems(): array
	{
		return [
			NavigationItem::make(static::getNavigationLabel())
				->group(static::getNavigationGroup())
				->parentItem(static::getNavigationParentItem())
				->icon(static::getNavigationIcon())
				->activeIcon(static::getActiveNavigationIcon())
				->isActiveWhen(fn (): bool => request()->routeIs(static::getRouteName()))
				->sort(static::getNavigationSort())
				->badge(static::getNavigationBadge(), color: static::getNavigationBadgeColor())
				->url(static::getNavigationUrl()),
		];
	}

**Comment by lorenzoaiello** [comment]
@danharrin, why was this closed? It's an active bug for Filament 3. Can you reopen this one, or do I need to make a new issue?

**Comment by adampatterson** [comment]
I had posted this in Discord since it's not always practical to link a git repo with the issue.

https://gist.github.com/adampatterson/75ec08f5938e0d26b851dd743726781c

I think when I was looking into this it had more to do with the `NavigationBuilder` but it's been months and I moved on.

**Comment by danharrin** [comment]
Since this issue was open, we did merge a PR to fix it, so please check you're on the latest version

> why was this closed

The user did not submit a reproduction repository

> it's not always practical to link a git repo with the issue

It may be inconvenient, but it is the only reason I am ok with fixing bugs for people. I've wasted enough time trying to reproducing bugs that only exist in someone's project, and I have plenty of work from people who are willing to put the effort in to help me out. If you're not going to put half an hour of work in to set up a new repository, then it's ok, I'm fine with the issue remaining closed 🤷‍♂️
