### ISSUE TITLE
Action $record returns parent model, and not the extended class when the extended class has "getMorphClass"

### ISSUE THREAD

**Issue by elfeffe** [laravel-filament/filament#7920]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.1

### Problem description

The mount function of the page (it's a custom page), says that $record is the correct class.
But the Action $record refers to the parent class, and not the extended one.

It only happens when getMorphClass exists int the extended class.

### Expected behavior

$record must be the extended class, as in the page

### Steps to reproduce

Extend a model, and use that model in a resource, then add getMorphClass to the extended class.
In the Reproduction repository, you can see an Action here Filament/Resources/Shop/CustomerResource/Pages/ScanCustomer.php

Filament/Resources/Shop/CustomerResource.php uses an extended Customer Model, called CustomerDemo.

If you remove getMorphClass it works, but as soon as you add getMorphClass it fails and tries to find the function in the parent class.

### Reproduction repository

https://github.com/elfeffe/filament-action-error

**Comment by najib7** [comment]
I faced the same issue and I fixed 

The problem is in livewire not filament exactly in class Livewire\Features\SupportModels\ModelSynth line 25 and 40.
The problem arises during the hydration of the Livewire component's when Livewire try to synthesize Model object, Livewire use the mapped morphclass as type of object or the FQN of class if no morph mapping exists for the class.

I hope I have clarified a little the problem 

In my example I have User class that extended by Teacher class
To fix this issue I create new livewire synthesizer (UserSynth) to transform Teacher model without using morphclass mapping

```
<?php

namespace App\Support\Livewire;

use App\Domain\User\Models\User;
use Illuminate\Queue\SerializesAndRestoresModelIdentifiers;
use Livewire\Mechanisms\HandleComponents\Synthesizers\Synth;

class UserSynth extends Synth
{
    use SerializesAndRestoresModelIdentifiers;

    public static string $key = 'userable';

    static function match($target)
    {
        return $target instanceof User;
    }

    public function dehydrate($target)
    {
        if (! $target->exists) {
            throw new \Exception('Can\'t set model as property if it hasn\'t been persisted yet');
        }

        $serializedModel = (array) $this->getSerializedPropertyValue($target);

        return [
            null,
            ['class' => $target::class, 'key' => $serializedModel['id']],
        ];
    }

    public function hydrate($data, $meta)
    {
        $key = $meta['key'];
        $class = $meta['class'];

        return (new $class)->newQueryForRestoration($key)->useWritePdo()->firstOrFail();
    }

    function get(&$target, $key) {
        throw new \Exception('Can\'t access model properties directly');
    }

    function set(&$target, $key, $value, $pathThusFar, $fullPath) {
        throw new \Exception('Can\'t set model properties directly');
    }

    function call($target, $method, $params, $addEffect) {
        throw new \Exception('Can\'t call model methods directly');
    }
}
```

And finally add this class to AppServiceProvider in boot method via

```
<?php

use App\Support\Livewire\UserSynth;
use Livewire\Livewire;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Livewire::propertySynthesizer(UserSynth::class);
        
        ...
    }
}
```

You can find more info about Livewire synthesizers in documentation: [https://livewire.laravel.com/docs/synthesizers#understanding-synthesizers](https://livewire.laravel.com/docs/synthesizers#understanding-synthesizers)

**Comment by danharrin** [comment]
Thanks @najib7!
