### ISSUE TITLE
Multi-Tenancy HasManyThrough Tenant Relationship

### ISSUE THREAD

**Issue by kylekanderson** [laravel-filament/filament#8029]
### Package

filament/filament

### Package Version

v3.0.23

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta.9

### PHP Version

PHP 8.2.9

### Problem description

When using Multi-Tenancy with a Resource where the Tenant has a HasManyThrough relationship to the Resource, the following error message is encountered upon trying to create a new record for the given Resource:

> Call to undefined method Illuminate\Database\Eloquent\Relations\HasManyThrough::save()

This error is originating from the following method: https://github.com/filamentphp/filament/blob/24fe227d68da7db6981c569926b55aadbe5f1a46/packages/panels/src/Resources/Pages/CreateRecord.php#L184

This method is attempting to call the `save` method on a HasManyThrough relationship, which is not supported by the Laravel framework.

This seems similar to the problem described in #7513 

### Expected behavior

In a Multi-Tenant environment, I should be able to create records for Resources which the Tenant has a HasManyThrough relationship to.

### Steps to reproduce

In a multi-tenant environment:

1. Create a Resource where the Tenant has a HasManyThrough relationship to the Resource
2. Attempt to create a new record for the resource
3. Observe error

### Reproduction repository

https://github.com/kylekanderson/filament-tenancy-hasmanythrough

**Comment by rodrigoliveirasantos** [comment]
This problem is still happening when creating record through modal. I have a model `Prefeitura` that has a HasManyThough relationship with an another model `Vistoria`. In the `VistoriaResource`, with the `Prefeitura` tenant, i'm getting the following error when trying to create a record though modal:

`Call to undefined method Illuminate\Database\Eloquent\Relations\HasManyThrough::save()`

The error is being triggered in `vendor/filament/actions/src/CreateAction.php :63`, by the code:

```php
$this->action(function (array $arguments, Form $form): void {
            $model = $this->getModel();

            $record = $this->process(function (array $data, HasActions $livewire) use ($model): Model {
                if ($translatableContentDriver = $livewire->makeFilamentTranslatableContentDriver()) {
                    $record = $translatableContentDriver->makeRecord($model, $data);
                } else {
                    $record = new $model;
                    $record->fill($data);
                }

                if ($relationship = $this->getRelationship()) {
                    /** @phpstan-ignore-next-line */
                    $relationship->save($record);

                    return $record;
                }

                $record->save();

                return $record;
            });
```

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/f8438189-5ed6-4b7a-b3f5-90816027f845" />
