### ISSUE TITLE
Button badges being truncated to 1 character

### ISSUE THREAD

**Issue by saade** [laravel-filament/filament#8092]
### Package

filament/filament

### Package Version

v3.0.34

### Laravel Version

10.20.0

### Livewire Version

dev-main

### PHP Version

8.2.9

### Problem description

Button badges are being truncated to 1 character

<img width="184" alt="image" src="https://github.com/filamentphp/filament/assets/14329460/afa5135a-5a98-4ed0-9fc4-db9900f3371c">

### Expected behavior

Badges should grow up to content length

### Steps to reproduce

```php
Action::make('changeStatus')
    ->label('Change status')
    ->icon('tabler-status-change')
    ->color('gray')
    ->badge('1225')
    ->outlined()
```

### Reproduction repository

https://github.com/saade/filament-reproduction-repo

**Comment by saade** [comment]
@zepfietje i don't think i need a repro repo for this, if you want one, let me know

**Comment by archilex** [comment]
Hi @saade This is a result of PR #8018, but it's being worked on.

**Comment by zepfietje** [comment]
Thanks for reporting, @saade.
I was aware of this issue and had already fixed it in https://github.com/filamentphp/filament/commit/b60c120771f80d59ef44ab00262ce64204c9b2a5.

However, no release has been tagged with that fix yet.
@danharrin will probably tag a release after I've implemented a fix for another issue later today.

If you like, you can verify this issue has been fixed by pulling in 3.x (but I'm very sure it's fixed 😉).
