### ISSUE TITLE
Not working the advanced disabled option 

### ISSUE THREAD

**Issue by gergo85** [laravel-filament/filament#8782]
### Package

filament/forms

### Package Version

v3.0.62

### Laravel Version

10.25.1

### PHP Version

8.2.4

### Problem description

To create an interactive form, one select field should affect another. I use advanced disable option, but nothing happened.

### Expected behavior

The field is not disabled.

### Steps to reproduce

I use this example code: ->disabled(fn (Get $get) => $get('print_all') == 1) 

### Reproduction repository

https://github.com/gergo85/filament-test-selectfield

**Comment by zepfietje** [comment]
Please read the docs: https://filamentphp.com/docs/3.x/forms/getting-started#dependant-fields.

Your first field should be `live()`.

**Comment by gergo85** [comment]
I used live() but no change.

**Comment by zepfietje** [comment]
With or without `native(false)` on the second field? Because the non-native select field doesn't support dynamically disabling it due to a limitation with Choices.js.

**Comment by gergo85** [comment]
Thanks for the quick response. Unfortunately, it doesn't work in either case.

**Comment by ilpav12** [comment]
@gergo85 with both select native it works but not on the first load because  `->default()` doesn't seem to change the value of the select.
It looks like even if you have have `->default(1)` on the first select, on the first load `$get('print_all')` is `null`.
If you change the value to 'No' and back to 'Yes' it correctly disable the second select.
A possible workaround is to `->disabled()` to check when `$get('print_all')` is `null` or 1.
Another is to remove both `->selectablePlaceholder(false)` and `->default(1)` to leave the user choose an option on the first select and trigger the disabling of the second.

**Comment by ilpav12** [comment]
I just saw the other issue, so I would say it is related to #8776.

**Comment by zepfietje** [comment]
Thanks, @ilpav12.
Closing as dupe.
