### ISSUE TITLE
Extra rows added to KV field when re-ordered in Builder field

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#9005]
### Package

filament/filament

### Package Version

3.0.73

### Laravel Version

10.2.6

### Livewire Version

3.0.7

### PHP Version

8.2

### Problem description

Video: https://www.youtube.com/watch?v=NhrMKYYAoWM

Additionally, these phantom rows can't be deleted (the delete button doesn't work)

### Expected behavior

Extra rows shouldn't be added when the KV field is moved.

### Steps to reproduce

See video

### Reproduction repository

https://github.com/binaryfire/filament-kv-bug

**Comment by binaryfire** [comment]
@danharrin This shouldn't have been auto-closed. I included a video which clearly demonstrates the issue and how to reproduce it.

**Comment by danharrin** [comment]
In the future, the video can go in the "Steps to reproduce" field, so the bot knows that you've put in some effort

**Comment by binaryfire** [comment]
I'm also occasionally seeing this when I try and delete blocks containing KV fields from a Builder field. Perhaps it sheds more light on the problem:

<img width="457" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/96edd725-9571-4fe4-a97b-cd0e44365798">

**Comment by danharrin** [comment]
I'm sorry, I've spent like 4 hours on this now and cannot narrow down what is happening, I'm going to have to move on. If anyone wants to do more research:

1. Rows arent actually getting added to the Alpine state
2. This is a problem with  the`x-for` something is replicating those template rows
3. It only happens when Sortable.js reorders the rows
4. This does not happen if the Alpine component is inline via `x-data`, or if it is registered via `Alpine.data()`. It only happens if the component is served with Async Alpine, so maybe that is part of what is wrong.

**Comment by awcodes** [comment]
PR submitted to dependency to fix this issue.

https://github.com/Accudio/async-alpine/pull/38
