### ISSUE TITLE
Dark mode Select Field Options Invisible

### ISSUE THREAD

**Issue by yellowbooth** [laravel-filament/filament#9598]
### Package

filament/forms

### Package Version

3.0-stable

### Laravel Version

10.10

### Livewire Version

3.0

### PHP Version

8.2.4

### Problem description

When using schema Select::make, the resultant unselected options show as white text on white background. Works perfectly in light mode or when hovering over an option.

### Expected behavior

Dark text on the white dropdown.

### Steps to reproduce

Standard laravel10/livewire3/filament3 installation out of the box. 
Add a select schema to a form:
                Select::make('permissions')->options([
                    'basic' => 'No permissions',
                    'dealer' => 'Dealer',
                    'admin' => 'Admin User',
                ]),
View in Chrome.
In firefox background is very light grey, so options can faintly be seen but still should be dark text.

### Reproduction repository

https://github.com/filamentphp/filament

### Relevant log output

```shell
Installed using:
composer require filament/filament:"^3.0-stable" -W
Not 100% if I have put the correct repository link (sorry!)
```

**Comment by ahamilton9** [comment]
For anyone who ends up here debugging the same issue this appears to be a Firefox-specific bug due to how styles are applied to \<select> fields. The \<option> elements can have their background and font colors adjusted, but the hovered \<option> will inherit system-styles for background color (gray) and use the \<select> element's font color. This means that while you can set the options to also have a dark background, the hovered option will only ever be readable if the Select element's font color is dark.

All the workarounds I found involving option:checked/hover and box-shadows no longer seem to work, so I resorted to making the \<select> revert to light-mode styles even in dark-mode. I'm sure there are better ways to target this but here is what I ended up with:

```css
/* Firefox only */
@supports (-moz-appearance:none) {
    .dark select {
        @apply rounded-lg;
        @apply bg-white;
        @apply !text-gray-900;
    }
    .dark select option {
        @apply !bg-white;
        @apply text-gray-900;
    }
}
```
