### ISSUE TITLE
Minimal Theme: issues when build

### ISSUE THREAD

**Issue by vlados** [laravel-filament/filament#9686]
### Package

filament/minimal-theme

### Package Version

v3.0.0.0.alpha8

### Laravel Version

v10.31.0

### Livewire Version

v3.1.0

### PHP Version

8.2.0

### Problem description

I followed the documentation for installing the theme, but when run `npm run build` I am getting:
```

> build
> vite build

vite v4.5.0 building for production...
transforming (44) node_modules/axios/lib/platform/browser/classes/URLSearchParams.js[vite:css] /Users/vlado/code/jcd/vendor/filament/minimal-theme/resources/css/infolists/split.css is empty

[vite:css] /Users/vlado/code/jcd/vendor/filament/minimal-theme/resources/css/notifications/database/modal/actions.css is empty
1  |  @import '/vendor/filament/minimal-theme/resources/css/index.css';
   |   ^
2  |
3  |  @config 'tailwind.config.js';
[vite:css] /Users/vlado/code/jcd/vendor/filament/minimal-theme/resources/css/widgets/chart-widget.css is empty
1  |  @import '/vendor/filament/minimal-theme/resources/css/index.css';
   |   ^
2  |
3  |  @config 'tailwind.config.js';
[vite:css] /Users/vlado/code/jcd/vendor/filament/minimal-theme/resources/css/widgets/table-widget.css is empty
1  |  @import '/vendor/filament/minimal-theme/resources/css/index.css';
2  |
3  |  @config 'tailwind.config.js';
   |   ^
4  |
✓ 48 modules transformed.
public/build/manifest.json                0.42 kB │ gzip:  0.17 kB
public/build/assets/app-501c80f4.css     34.53 kB │ gzip:  6.34 kB
public/build/assets/theme-35fa3c04.css  124.22 kB │ gzip: 16.90 kB
public/build/assets/app-22752a76.js      29.53 kB │ gzip: 11.86 kB
✓ built in 718ms
````

### Expected behavior

To run without errors

### Steps to reproduce

create a clean project and install the theme

### Reproduction repository

private

**Comment by man0l** [comment]
I have the same issue with the Minimal Theme ... I am not quite sure if it has any styles rather than the default filament theme.
The files are empty itself, I checked out.

**Comment by vlados** [comment]
For me that was more like donation than something that I will use

**Comment by zepfietje** [comment]
Hey @vlados and @man0l, sorry for missing this issue!

The logs you reported are just warnings that certain files were empty.
As I was working on the theme, I had created a skeleton to make sure that all Filament components are covered.
So the logs can just be ignored as the assets are built successfully (as seen in the logs you posted).
Couple weeks ago I actually made sure there's no empty files any more, so your terminal stays clean when building. 😉

> I am not quite sure if it has any styles rather than the default filament theme.

The theme certainly provides a lot of styles (I revisited every single component and view). Make sure to update to the latest version and check you've completely followed the installation instructions.

If y'all have any more questions, you can reach me via email (otherwise I won't get notified). 🙂
