### ISSUE TITLE
First tab should be shown on validation error

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#9832]
First tab should be shown on validation error. Currently the last tab gets shown. Also, it should scroll to the first validation error instead of the top of the tab.

**Comment by drbyte** [comment]
Yes, I've avoided form-wizards because of this problem.

I would suggest that it should jump to the tab where the first validation error occurs, not necessarily the 'first' tab.

I'm not sure how doable this is, but: I would also suggest that the Submit button should also have some indicator added to it (even error text below it like a typical validation error) indicating that errors were found, which is why the form didn't submit when clicked.

**Comment by zepfietje** [comment]
With first tab I mean the first tab with validation errors.

Don't see the need for an indicator on the submit button when validation errors are scrolled into view.

**Comment by drbyte** [comment]
Fair point. 

I didn't fully explain the context I was commenting from: I think I was thinking of tabs differently than you were.
Given that I was recently working with a many-steps-wizard form, I immediately thought of a "wizard step" as a "tab". In such case, the submit button on the last "tab"/step of a wizard form might have nothing to scroll into view if the validation error for the forum is on a prior tab/step. Hence my comment above.

**Comment by zepfietje** [comment]
I see your point, though on resubmitting the form after fixing errors in one tab, the other tab will be shown. Can't think of a better way to handle that honestly. Also, let's not pollute this issue. Feel free to open a PR or discussion for your request. 😊

**Comment by drbyte** [comment]
Agreed.
