### ISSUE TITLE
Unable to add blocks to builder field after 3.1 update

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#9954]
### Package

filament/filament

### Package Version

v3.1.0

### Laravel Version

v10.34.0

### Livewire Version

v3.2.1

### PHP Version

v8.2

### Problem description

Blocks are no longer added to builder fields after clicking a block in the picker. This started happening after the v3.1 update.

### Expected behavior

Blocks should be added when clicked in the picker.

### Steps to reproduce

Install the reproduction repo, create a new "Builder tests" item, then try and add blocks.

### Reproduction repository

https://github.com/binaryfire/filament-kv-bug

**Comment by binaryfire** [comment]
PS. Just ignore the repo name. This is an existing reproduction repo for a different bug.

**Comment by danharrin** [comment]
Seems to only be an issue with builders inside sections

**Comment by danharrin** [comment]
In fact, it's only builders inside sections with the heading "Builder"

This is because, sections with the heading "Builder" have an auto-generated id() of `builder`

And the ID of the builder component is also `builder`

Form components must have unique IDs in order for form component actions to work correctly

So the fix is `Section::make()->id('builder-section')`

The reason why this has just started, is because we introduced section header actions, which rely on the ID existing for section. To make it easier to use, we added the ID generation by default, but now the IDs clash.

**Comment by danharrin** [comment]
I've just pushed up a fix to remove the ID autogeneration when there are no header actions, so this shouldnt be a BC anymore.

**Comment by binaryfire** [comment]
Makes sense. Would never have figured that out - thanks for the explanation.
